### PR TITLE
Updated hexToRGB

### PR DESCRIPTION
**Pull request by JonasNiestroj**
Hey,

i updated the hexToRGB function. 
The newer one has a better performance and also can handle shorthand hex colors (e.g. '#fc0')

### CODE REVIEW

**Comment by precyx** [comment]
Hey Jonas, very nice, thanks for contributing.
It's working for 6 digit hex values, but I think it's converting to the wrong color when using 3 digi hex'.

example:
https://codepen.io/anon/pen/MMZmvq

**Comment by JonasNiestroj** [comment]
Hey,
Yeah you were right. I've added a regex to convert the shorthand hex to a normal 6 digit hex. 
Now it should work with every hex.

Working example:
https://codepen.io/anon/pen/YodQyQ

**Comment by precyx** [comment]
Looking good thanks!

**Comment by rotwurstesser** [comment]
@JonasNiestroj thank you <3

**Pull request merged**
